sudo: required
services:
  - docker
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=louisvernon/shields
before_install:
  - docker build -t $REPO:$COMMIT . 

script:
  - docker run -it $REPO:$COMMIT /bin/bash -c "ls"

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $REPO
